import { describe, expect, it } from "vitest";

describe("M33 — Report export and analyst integration", () => {
  it("POST /api/reports/export accepts lens + format", () => {
    const body = { lens: "ecosystem", format: "markdown" };
    expect(body.lens).toBe("ecosystem");
    expect(body.format).toBe("markdown");
  });

  it("export format can be markdown or json", () => {
    const formats = ["markdown", "json"];
    for (const f of formats) {
      expect(f).toMatch(/^(markdown|json)$/);
    }
  });

  it("GET /api/reports/evaluated exposes quality verdict", () => {
    // The endpoint returns { report, verdict } where verdict has quality
    const mockResponse = {
      report: { id: "r-001", lens: "ecosystem", confidence: "medium" },
      verdict: {
        reportId: "r-001",
        confidence: "medium",
        quality: "fair",
        hasVerifiedEvidence: true,
        evidence: { total: 5, verified: 2, demo: 0, weight: 0.8, confidence: "medium" },
      },
    };
    expect(mockResponse.verdict.quality).toMatch(/^(poor|fair|good)$/);
    expect(mockResponse.verdict.evidence.total).toBe(5);
  });

  it("GET /api/reports/[id]/artifact retrieves from ObjectStore", () => {
    const mockArtifact = {
      reportId: "r-001",
      artifact: { id: "r-001", title: "Ecosystem Report" },
    };
    expect(mockArtifact.artifact.id).toBe("r-001");
  });

  it("POST /api/saved with kind=report requires reportId + lens", () => {
    const body = { kind: "report", reportId: "r-001", lens: "ecosystem", title: "Test" };
    expect(body.kind).toBe("report");
    expect(body.reportId).toBeDefined();
    expect(body.lens).toBeDefined();
  });

  it("POST /api/saved with kind=project requires projectId", () => {
    const body = { kind: "project", projectId: "jupiter", name: "Jupiter" };
    expect(body.kind).toBe("project");
    expect(body.projectId).toBeDefined();
  });

  it("POST /api/saved with kind=narrative requires narrativeId", () => {
    const body = { kind: "narrative", narrativeId: "n-001", name: "LST Growth" };
    expect(body.kind).toBe("narrative");
    expect(body.narrativeId).toBeDefined();
  });

  it("markdown export includes report sections and evidence", () => {
    const mockMarkdown = [
      "# Solana Ecosystem Overview",
      "",
      "**Lens:** ecosystem",
      "**Confidence:** medium",
      "",
      "## Executive Summary",
      "",
      "The ecosystem is healthy.",
      "",
      "## Evidence Log",
      "",
      "- **[ev-001]** Helius — Jupiter TVL verified (verified)",
      "",
      "---",
      "*Generated by Insight. Not investment advice.*",
    ].join("\n");
    expect(mockMarkdown).toContain("# Solana Ecosystem Overview");
    expect(mockMarkdown).toContain("## Executive Summary");
    expect(mockMarkdown).toContain("## Evidence Log");
    expect(mockMarkdown).toContain("[ev-001]");
    expect(mockMarkdown).toContain("Not investment advice");
  });

  it("json export includes report + evidence objects", () => {
    const mockJson = JSON.stringify({
      report: { id: "r-001", title: "Test", sections: { thesis: "Test thesis" } },
      evidence: [{ id: "ev-001", source: { name: "Helius" }, note: "test", status: "verified" }],
    });
    const parsed = JSON.parse(mockJson);
    expect(parsed.report.id).toBe("r-001");
    expect(parsed.evidence[0].id).toBe("ev-001");
  });
});
