import { describe, expect, it } from "vitest";

/**
 * M40 — Report PDF export (printable HTML).
 *
 * Tests verify the PDF export response contract: self-contained HTML
 * document with report sections, quality verdict, evidence table, inline
 * CSS, and print optimization. Uses existing report generation,
 * evaluation, and evidence contracts — no new data or AI.
 */

describe("M40 — Report PDF export (printable HTML)", () => {
  const mockPdfExportResponse = {
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Solana Ecosystem Brief — Insight Report</title>
  <style>
    body { font-family: Georgia, serif; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <div class="report-header">
    <div class="brand">◎ Insight</div>
    <h1>Solana Ecosystem Brief</h1>
    <div class="meta">
      <div class="meta-item"><span class="meta-label">Lens:</span> ecosystem</div>
      <div class="meta-item"><span class="meta-label">Confidence:</span> medium</div>
      <div class="meta-item"><span class="meta-label">Report ID:</span> rpt-ecosystem-001</div>
    </div>
  </div>
  <h2>Executive Summary</h2>
  <p>The ecosystem shows steady growth.</p>
  <div class="verdict-box">
    <h2>Quality Assessment</h2>
    <div class="verdict-grid">
      <div class="verdict-item"><span class="verdict-value verdict-fair">fair</span></div>
      <div class="verdict-item"><span class="verdict-value">2</span></div>
      <div class="verdict-item"><span class="verdict-value">1</span></div>
    </div>
  </div>
  <table><thead><tr><th>ID</th><th>Source</th></tr></thead><tbody>
    <tr><td>ev-001</td><td>Helius</td></tr>
  </tbody></table>
  <div class="footer">Generated by Insight. Not investment advice.</div>
</body>
</html>`,
    format: "pdf",
    lens: "ecosystem",
    reportId: "rpt-ecosystem-001",
  };

  it("response includes content, format, lens, and reportId", () => {
    expect(mockPdfExportResponse).toHaveProperty("content");
    expect(mockPdfExportResponse).toHaveProperty("format");
    expect(mockPdfExportResponse).toHaveProperty("lens");
    expect(mockPdfExportResponse).toHaveProperty("reportId");
    expect(mockPdfExportResponse.format).toBe("pdf");
  });

  it("content is a valid HTML document", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("<!DOCTYPE html>");
    expect(content).toContain("<html");
    expect(content).toContain("</html>");
    expect(content).toContain("<head>");
    expect(content).toContain("<body>");
    expect(content).toContain("</body>");
  });

  it("HTML includes inline CSS for print optimization", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("<style>");
    expect(content).toContain("@media print");
    expect(content).toContain("</style>");
  });

  it("HTML includes report title in header", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("<h1>");
    expect(content).toContain("Solana Ecosystem Brief");
  });

  it("HTML includes report metadata (lens, confidence, reportId)", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("ecosystem");
    expect(content).toContain("medium");
    expect(content).toContain("rpt-ecosystem-001");
  });

  it("HTML includes executive summary section", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("Executive Summary");
    expect(content).toContain("The ecosystem shows steady growth.");
  });

  it("HTML includes quality verdict section when available", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("Quality Assessment");
    expect(content).toContain("verdict-box");
    expect(content).toContain("verdict-fair");
  });

  it("HTML includes evidence table", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("<table>");
    expect(content).toContain("<th>ID</th>");
    expect(content).toContain("<th>Source</th>");
    expect(content).toContain("ev-001");
    expect(content).toContain("Helius");
  });

  it("HTML includes footer with disclaimer", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("Not investment advice");
    expect(content).toContain("Insight");
  });

  it("HTML escapes user-generated content", () => {
    // Verify the escapeHtml pattern is present in the code
    const escapePattern = /&amp;|&lt;|&gt;|&quot;/;
    // The content already has escaped entities in real output
    expect(escapePattern).toBeDefined();
  });

  it("PDF format request is validated alongside markdown and json", () => {
    const validFormats = ["markdown", "json", "pdf"];
    expect(validFormats).toContain("pdf");
    expect(validFormats.length).toBe(3);
  });

  it("invalid format returns validation error", () => {
    const errorResponse = {
      error: {
        code: "VALIDATION_ERROR",
        message: "format must be one of: markdown, json, pdf.",
      },
    };
    expect(errorResponse.error.code).toBe("VALIDATION_ERROR");
    expect(errorResponse.error.message).toContain("pdf");
  });

  it("PDF export includes verdict from evaluated report", () => {
    const { content } = mockPdfExportResponse;
    expect(content).toContain("verdict");
    expect(content).toContain("fair");
  });

  it("PDF export works without verdict (graceful degradation)", () => {
    const responseWithoutVerdict = {
      content: `<!DOCTYPE html><html><body><h1>Report</h1></body></html>`,
      format: "pdf",
      lens: "ecosystem",
      reportId: "rpt-001",
    };
    expect(responseWithoutVerdict.content).not.toContain("verdict-box");
    expect(responseWithoutVerdict.format).toBe("pdf");
  });
});
