import type { Report, ReportGeneratorConfig } from "./ReportTypes";
import type { IntelligenceSignal } from "@insight/intelligence";

/**
 * HtmlRenderer — Renders Report to standalone HTML.
 *
 * No framework, no React, no CSS library.
 * Pure HTML + inline CSS for portability.
 */

export class HtmlRenderer {
  render(report: Report, config: ReportGeneratorConfig): string {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(report.title)}</title>
  <style>
    ${this.getStyles()}
  </style>
</head>
<body>
  <div class="container">
    ${this.renderHeader(report, config)}
    ${config.includeMetadata ? this.renderMetadata(report) : ""}
    ${config.includeSummary ? this.renderSummary(report) : ""}
    ${config.includeSignalDetails ? this.renderSignals(report) : ""}
    <footer class="footer">
      Generated by Insight Report Generator v${report.metadata.generatorVersion} at ${new Date(report.generatedAt).toISOString()}
    </footer>
  </div>
</body>
</html>`;

    return html;
  }

  private getStyles(): string {
    return `
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; background: #f8f9fa; padding: 20px; }
.container { max-width: 900px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.08); padding: 40px; }
h1 { color: #1a1a2e; font-size: 2rem; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #e8e8f0; }
h2 { color: #2d2d44; font-size: 1.4rem; margin: 2rem 0 1rem; padding-bottom: 0.3rem; border-bottom: 1px solid #e8e8f0; }
h3 { color: #3d3d5c; font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
p { margin: 0.5rem 0; }
ul { margin: 0.5rem 0 0.5rem 1.5rem; }
li { margin: 0.25rem 0; }
code { background: #f0f0f5; padding: 0.15rem 0.4rem; border-radius: 4px; font-family: "SF Mono", Monaco, monospace; font-size: 0.9em; }
pre { background: #1e1e2e; color: #e0e0e8; padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 1rem 0; }
pre code { background: none; padding: 0; }
.metadata-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0; }
.metadata-item { background: #f8f9fa; padding: 1rem; border-radius: 6px; border-left: 3px solid #4a6cf7; }
.metadata-label { font-size: 0.75rem; text-transform: uppercase; color: #6b6b8a; letter-spacing: 0.5px; margin-bottom: 0.25rem; }
.metadata-value { font-weight: 600; color: #1a1a2e; }
.summary-box { background: #f0f4ff; border-left: 4px solid #4a6cf7; padding: 1.5rem; border-radius: 0 6px 6px 0; margin: 1rem 0; }
.signal-card { background: #fafafa; border: 1px solid #e8e8f0; border-radius: 8px; padding: 1.5rem; margin: 1rem 0; transition: box-shadow 0.2s; }
.signal-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
.signal-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem; flex-wrap: wrap; gap: 0.5rem; }
.signal-title { font-size: 1.1rem; font-weight: 600; color: #1a1a2e; }
.signal-type { background: #e8ecff; color: #4a6cf7; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
.signal-meta { display: flex; gap: 1.5rem; flex-wrap: wrap; margin: 0.5rem 0; font-size: 0.85rem; color: #555; }
.signal-meta-item { display: flex; align-items: center; gap: 0.35rem; }
.signal-meta-label { color: #888; }
.signal-meta-value { font-weight: 500; }
.signal-description { color: #333; margin: 1rem 0; line-height: 1.7; }
.signal-evidence { background: #f8f9fa; border-radius: 6px; padding: 1rem; margin: 1rem 0; }
.signal-evidence-title { font-size: 0.85rem; font-weight: 600; color: #555; margin-bottom: 0.5rem; }
.signal-evidence-list { list-style: none; margin: 0; padding: 0; }
.signal-evidence-list li { background: white; padding: 0.5rem 0.75rem; border-radius: 4px; margin: 0.35rem 0; border: 1px solid #e8e8f0; font-size: 0.85rem; }
.signal-metadata { margin-top: 1rem; }
.footer { text-align: center; color: #888; font-size: 0.75rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e8e8f0; }
.empty-state { text-align: center; color: #888; padding: 3rem; }
@media (max-width: 600px) {
  .container { padding: 20px; }
  .metadata-grid { grid-template-columns: 1fr; }
}`;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&#38;")
      .replace(/</g, "&#60;")
      .replace(/>/g, "&#62;")
      .replace(/"/g, "&#34;")
      .replace(/'/g, "'");
  }

  private renderHeader(report: Report, config: ReportGeneratorConfig): string {
    return `
    <header class="report-header">
      <h1>${this.escapeHtml(report.title)}</h1>
      <div class="signal-meta">
        <span class="signal-meta-item">
          <span class="signal-meta-label">Report ID:</span>
          <span class="signal-meta-value">${this.escapeHtml(report.id)}</span>
        </span>
        <span class="signal-meta-item">
          <span class="signal-meta-label">Generated:</span>
          <span class="signal-meta-value">${new Date(report.generatedAt).toLocaleString()}</span>
        </span>
      </div>
    </header>`;
  }

  private renderMetadata(report: Report): string {
    return `
    <section class="report-section">
      <h2>Metadata</h2>
      <div class="metadata-grid">
        <div class="metadata-item">
          <div class="metadata-label">Signal Count</div>
          <div class="metadata-value">${report.metadata.signalCount}</div>
        </div>
        <div class="metadata-item">
          <div class="metadata-label">Signal Types</div>
          <div class="metadata-value">${report.metadata.signalTypes.join(", ") || "&mdash;"}</div>
        </div>
        <div class="metadata-item">
          <div class="metadata-label">Avg Confidence</div>
          <div class="metadata-value">${(report.metadata.avgConfidence * 100).toFixed(1)}%</div>
        </div>
        <div class="metadata-item">
          <div class="metadata-label">Generator Version</div>
          <div class="metadata-value">${report.metadata.generatorVersion}</div>
        </div>
      </div>
    </section>`;
  }

  private renderSummary(report: Report): string {
    return `
    <section class="report-section">
      <h2>Summary</h2>
      <div class="summary-box">${this.escapeHtml(report.summary)}</div>
    </section>`;
  }

  private renderSignals(report: Report): string {
    if (report.signals.length === 0) {
      return `
      <section class="report-section">
        <h2>Signals</h2>
        <div class="empty-state">No signals generated.</div>
      </section>`;
    }

    const signalsHtml = report.signals
      .map((signal, index) => this.renderSignal(signal, index))
      .join("");

    return `
    <section class="report-section">
      <h2>Signals (${report.signals.length})</h2>
      ${signalsHtml}
    </section>`;
  }

  private renderSignal(signal: IntelligenceSignal, index: number): string {
    const escape = this.escapeHtml.bind(this);

    const evidenceHtml =
      signal.supportingEvidence && signal.supportingEvidence.length > 0
        ? `
      <div class="signal-evidence">
        <div class="signal-evidence-title">Supporting Evidence</div>
        <ul class="signal-evidence-list">
          ${signal.supportingEvidence
            .map(
              (ev) =>
                `<li>${escape(ev.evidenceId)}: ${escape(ev.relationship)} (weight: ${(ev.weight ?? 1).toFixed(2)})</li>`,
            )
            .join("")}
        </ul>
      </div>`
        : "";

    const metadataHtml = signal.metadata
      ? `
      <div class="signal-metadata">
        <div class="signal-evidence-title">Metadata</div>
        <pre><code>${escape(JSON.stringify(signal.metadata, null, 2))}</code></pre>
      </div>`
      : "";

    return `
    <article class="signal-card">
      <div class="signal-header">
        <h3 class="signal-title">${index + 1}. ${escape(signal.title)}</h3>
        <span class="signal-type">${escape(signal.type)}</span>
      </div>
      <div class="signal-meta">
        <div class="signal-meta-item">
          <span class="signal-meta-label">Confidence:</span>
          <span class="signal-meta-value">${(signal.confidence * 100).toFixed(1)}%</span>
        </div>
        <div class="signal-meta-item">
          <span class="signal-meta-label">Evidence Refs:</span>
          <span class="signal-meta-value">${signal.evidenceIds.length}</span>
        </div>
        <div class="signal-meta-item">
          <span class="signal-meta-label">Timestamp:</span>
          <span class="signal-meta-value">${new Date(signal.timestamp).toLocaleString()}</span>
        </div>
      </div>
      <div class="signal-description">${escape(signal.description)}</div>
      ${evidenceHtml}
      ${metadataHtml}
    </article>`;
  }
}
