import { getInsightService } from "../../../../lib/insight-service";
import { errorFromUnknown, errorResponse, ok, requestIdFromRequest } from "../../../../lib/api";
import { validateReportLens } from "@insight/runtime";
import type { Report, Evidence } from "@insight/core";
import type { ReportVerdict } from "@insight/infra";

/**
 * POST /api/reports/export — export a report as markdown, JSON, or PDF (printable HTML).
 *
 * Request: { "lens": "ecosystem", "format": "markdown" | "json" | "pdf" }
 * Response: { content, format, lens, reportId }
 *
 * Generates a shareable, source-backed report export with evidence citations
 * and quality verdict (for PDF). The PDF format produces a self-contained
 * HTML document optimized for browser print-to-PDF.
 */
export async function POST(request: Request): Promise<Response> {
  const requestId = requestIdFromRequest(request);
  try {
    const body = (await request.json().catch(() => null)) as {
      lens?: string;
      format?: string;
    } | null;

    const rawLens = body?.lens ?? "ecosystem";
    const format = body?.format ?? "markdown";

    const lensResult = validateReportLens(rawLens);
    if (!lensResult.ok) {
      return errorResponse(
        "VALIDATION_ERROR",
        lensResult.error.message,
        400,
        lensResult.error.details,
        requestId,
      );
    }

    const validFormats = ["markdown", "json", "pdf"];
    if (!validFormats.includes(format)) {
      return errorResponse(
        "VALIDATION_ERROR",
        `format must be one of: ${validFormats.join(", ")}.`,
        400,
        undefined,
        requestId,
      );
    }

    const service = getInsightService();
    await service.ready();
    const report = await service.getReport(lensResult.value);
    if (report === undefined) {
      return errorResponse(
        "NOT_FOUND",
        `No report available for lens "${lensResult.value}".`,
        404,
        undefined,
        requestId,
      );
    }

    // Resolve evidence for citations
    const evidence = await service.resolveEvidenceIds(report.evidenceIds);

    if (format === "json") {
      return ok({
        content: JSON.stringify({ report, evidence }, null, 2),
        format: "json",
        lens: report.lens,
        reportId: report.id,
      });
    }

    if (format === "pdf") {
      // M40: Include quality verdict in the PDF export
      const evaluated = await service.getEvaluatedReport(lensResult.value);
      const verdict = evaluated?.verdict;
      const content = reportToPrintableHTML(report, evidence, verdict);
      return ok({
        content,
        format: "pdf",
        lens: report.lens,
        reportId: report.id,
      });
    }

    // Markdown export
    const content = reportToMarkdown(report, evidence);
    return ok({
      content,
      format: "markdown",
      lens: report.lens,
      reportId: report.id,
    });
  } catch (error) {
    return errorFromUnknown(error, requestId);
  }
}

function reportToMarkdown(
  report: Report,
  evidence: readonly {
    id: string;
    source: { name: string };
    note: string;
    status: string;
    reference?: string;
  }[],
): string {
  const lines: string[] = [];
  lines.push(`# ${report.title}`);
  lines.push("");
  lines.push(`**Lens:** ${report.lens}`);
  lines.push(`**Confidence:** ${report.confidence}`);
  lines.push(`**Generated:** ${report.generatedAt}`);
  lines.push(`**Report ID:** ${report.id}`);
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(report.sections.thesis);
  lines.push("");
  if (report.sections.catalyst) {
    lines.push("## What Could Matter Next");
    lines.push("");
    lines.push(report.sections.catalyst);
    lines.push("");
  }
  if (report.sections.risk) {
    lines.push("## Research Caveat");
    lines.push("");
    lines.push(report.sections.risk);
    lines.push("");
  }
  if (evidence.length > 0) {
    lines.push("## Evidence Log");
    lines.push("");
    for (const e of evidence) {
      lines.push(`- **[${e.id}]** ${e.source.name} — ${e.note} (${e.status})`);
      if (e.reference) {
        lines.push(`  - Reference: ${e.reference}`);
      }
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("*Generated by Insight. Not investment advice.*");
  return lines.join("\n");
}

/**
 * M40: Generate a self-contained, print-optimized HTML document
 * for browser print-to-PDF. Includes report sections, quality verdict,
 * and evidence log with inline CSS — no external dependencies.
 */
function reportToPrintableHTML(
  report: Report,
  evidence: readonly Evidence[],
  verdict?: ReportVerdict,
): string {
  const escapeHtml = (text: string): string =>
    text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

  const evidenceRows = evidence
    .map(
      (e) => `
        <tr>
          <td>${escapeHtml(e.id)}</td>
          <td>${escapeHtml(e.source.name)}</td>
          <td>${escapeHtml(e.note)}</td>
          <td><span class="status status-${e.status}">${escapeHtml(e.status)}</span></td>
          ${e.reference ? `<td>${escapeHtml(e.reference)}</td>` : "<td>—</td>"}
        </tr>`,
    )
    .join("");

  const verdictSection = verdict
    ? `
      <div class="verdict-box">
        <h2>Quality Assessment</h2>
        <div class="verdict-grid">
          <div class="verdict-item">
            <span class="verdict-label">Quality</span>
            <span class="verdict-value verdict-${verdict.quality}">${escapeHtml(verdict.quality)}</span>
          </div>
          <div class="verdict-item">
            <span class="verdict-label">Confidence</span>
            <span class="verdict-value">${escapeHtml(verdict.confidence)}</span>
          </div>
          <div class="verdict-item">
            <span class="verdict-label">Evidence Items</span>
            <span class="verdict-value">${verdict.evidence.total}</span>
          </div>
          <div class="verdict-item">
            <span class="verdict-label">Verified</span>
            <span class="verdict-value">${verdict.evidence.verified}</span>
          </div>
          <div class="verdict-item">
            <span class="verdict-label">Demo</span>
            <span class="verdict-value">${verdict.evidence.demo}</span>
          </div>
          <div class="verdict-item">
            <span class="verdict-label">Verified Evidence</span>
            <span class="verdict-value">${verdict.hasVerifiedEvidence ? "Yes" : "No"}</span>
          </div>
        </div>
      </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(report.title)} — Insight Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: Georgia, "Times New Roman", serif;
      color: #17211b;
      background: #fff;
      line-height: 1.6;
      padding: 48px;
      max-width: 800px;
      margin: 0 auto;
    }
    .report-header { border-bottom: 2px solid #17211b; padding-bottom: 24px; margin-bottom: 32px; }
    .brand { font-size: 14px; font-weight: 700; letter-spacing: 0.14em; color: #7247eb; text-transform: uppercase; }
    h1 { font-size: 32px; line-height: 1.15; margin: 12px 0 8px; }
    .meta { font-size: 13px; color: #647068; display: flex; gap: 24px; flex-wrap: wrap; }
    .meta-item { display: flex; gap: 6px; }
    .meta-label { font-weight: 600; color: #17211b; }
    h2 { font-size: 20px; margin: 28px 0 12px; font-family: Arial, Helvetica, sans-serif; }
    p { font-size: 15px; margin-bottom: 12px; }
    .verdict-box {
      background: #f7f8f5;
      border: 1px solid #dce3dc;
      border-radius: 8px;
      padding: 20px;
      margin: 24px 0;
    }
    .verdict-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      margin-top: 12px;
    }
    .verdict-item { display: flex; flex-direction: column; gap: 2px; }
    .verdict-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #647068; }
    .verdict-value { font-size: 16px; font-weight: 700; }
    .verdict-good { color: #2e7d32; }
    .verdict-fair { color: #f57f17; }
    .verdict-poor { color: #c62828; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
      font-size: 13px;
    }
    th, td {
      text-align: left;
      padding: 8px 10px;
      border-bottom: 1px solid #dce3dc;
    }
    th {
      font-family: Arial, Helvetica, sans-serif;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      color: #647068;
    }
    .status {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 99px;
      font-size: 11px;
      font-weight: 600;
    }
    .status-verified { background: #e8f5e9; color: #2e7d32; }
    .status-demo { background: #fff8e1; color: #f57f17; }
    .status-pending { background: #e3f2fd; color: #1565c0; }
    .status-draft { background: #f5f5f5; color: #616161; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #dce3dc;
      font-size: 12px;
      color: #647068;
      text-align: center;
    }
    @media print {
      body { padding: 24px; max-width: none; }
      .verdict-box { break-inside: avoid; }
      table { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="report-header">
    <div class="brand">◎ Insight</div>
    <h1>${escapeHtml(report.title)}</h1>
    <div class="meta">
      <div class="meta-item"><span class="meta-label">Lens:</span> ${escapeHtml(report.lens)}</div>
      <div class="meta-item"><span class="meta-label">Confidence:</span> ${escapeHtml(report.confidence)}</div>
      <div class="meta-item"><span class="meta-label">Generated:</span> ${escapeHtml(report.generatedAt)}</div>
      <div class="meta-item"><span class="meta-label">Report ID:</span> ${escapeHtml(report.id)}</div>
    </div>
  </div>

  <h2>Executive Summary</h2>
  <p>${escapeHtml(report.sections.thesis)}</p>

  ${report.sections.catalyst ? `<h2>What Could Matter Next</h2><p>${escapeHtml(report.sections.catalyst)}</p>` : ""}

  ${report.sections.risk ? `<h2>Research Caveat</h2><p>${escapeHtml(report.sections.risk)}</p>` : ""}

  ${verdictSection}

  ${
    evidence.length > 0
      ? `
  <h2>Evidence Log</h2>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Source</th>
        <th>Note</th>
        <th>Status</th>
        <th>Reference</th>
      </tr>
    </thead>
    <tbody>
      ${evidenceRows}
    </tbody>
  </table>`
      : ""
  }

  <div class="footer">
    Generated by Insight — evidence-first research for the Solana ecosystem.<br />
    Not investment advice.
  </div>
</body>
</html>`;
}
