import { getInsightService } from "../../../../lib/insight-service";
import { errorFromUnknown, errorResponse, ok, requestIdFromRequest } from "../../../../lib/api";
import { validateReportLens } from "@insight/runtime";
import type { Report } from "@insight/core";

/**
 * POST /api/reports/export — export a report as markdown or JSON.
 *
 * Request: { "lens": "ecosystem", "format": "markdown" | "json" }
 * Response: { content, format, lens, reportId }
 *
 * Generates a shareable, source-backed report export with evidence citations.
 */
export async function POST(request: Request): Promise<Response> {
  const requestId = requestIdFromRequest(request);
  try {
    const body = (await request.json().catch(() => null)) as {
      lens?: string;
      format?: string;
    } | null;

    const rawLens = body?.lens ?? "ecosystem";
    const format = body?.format ?? "markdown";

    const lensResult = validateReportLens(rawLens);
    if (!lensResult.ok) {
      return errorResponse(
        "VALIDATION_ERROR",
        lensResult.error.message,
        400,
        lensResult.error.details,
        requestId,
      );
    }

    if (format !== "markdown" && format !== "json") {
      return errorResponse(
        "VALIDATION_ERROR",
        'format must be "markdown" or "json".',
        400,
        undefined,
        requestId,
      );
    }

    const service = getInsightService();
    await service.ready();
    const report = await service.getReport(lensResult.value);
    if (report === undefined) {
      return errorResponse(
        "NOT_FOUND",
        `No report available for lens "${lensResult.value}".`,
        404,
        undefined,
        requestId,
      );
    }

    // Resolve evidence for citations
    const evidence = await service.resolveEvidenceIds(report.evidenceIds);

    if (format === "json") {
      return ok({
        content: JSON.stringify({ report, evidence }, null, 2),
        format: "json",
        lens: report.lens,
        reportId: report.id,
      });
    }

    // Markdown export
    const content = reportToMarkdown(report, evidence);
    return ok({
      content,
      format: "markdown",
      lens: report.lens,
      reportId: report.id,
    });
  } catch (error) {
    return errorFromUnknown(error, requestId);
  }
}

function reportToMarkdown(
  report: Report,
  evidence: readonly {
    id: string;
    source: { name: string };
    note: string;
    status: string;
    reference?: string;
  }[],
): string {
  const lines: string[] = [];
  lines.push(`# ${report.title}`);
  lines.push("");
  lines.push(`**Lens:** ${report.lens}`);
  lines.push(`**Confidence:** ${report.confidence}`);
  lines.push(`**Generated:** ${report.generatedAt}`);
  lines.push(`**Report ID:** ${report.id}`);
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(report.sections.thesis);
  lines.push("");
  if (report.sections.catalyst) {
    lines.push("## What Could Matter Next");
    lines.push("");
    lines.push(report.sections.catalyst);
    lines.push("");
  }
  if (report.sections.risk) {
    lines.push("## Research Caveat");
    lines.push("");
    lines.push(report.sections.risk);
    lines.push("");
  }
  if (evidence.length > 0) {
    lines.push("## Evidence Log");
    lines.push("");
    for (const e of evidence) {
      lines.push(`- **[${e.id}]** ${e.source.name} — ${e.note} (${e.status})`);
      if (e.reference) {
        lines.push(`  - Reference: ${e.reference}`);
      }
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("*Generated by Insight. Not investment advice.*");
  return lines.join("\n");
}
